# Generated by Django 4.1 on 2026-04-21 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='分类名称', max_length=10, verbose_name='分类')),
            ],
            options={
                'verbose_name': '分类管理',
                'verbose_name_plural': '分类管理',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cover', models.ImageField(blank=True, help_text='最佳尺寸:', null=True, upload_to='news', verbose_name='封面')),
                ('title', models.CharField(help_text='资讯', max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('creat_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('categroy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
            ],
            options={
                'verbose_name': '资讯',
                'verbose_name_plural': '资讯',
                'db_table': 'news',
            },
        ),
    ]
