# Generated by Django 4.2 on 2026-04-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='categroy',
            new_name='category',
        ),
    ]
