# Generated by Django 4.2 on 2026-04-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('development_history_time', models.CharField(help_text='填写年份', max_length=20, verbose_name='发展时间')),
                ('development_history_content', models.TextField(verbose_name='发展历程')),
            ],
            options={
                'verbose_name': '关于我们',
                'verbose_name_plural': '关于我们',
                'db_table': 'about_us',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='最佳尺寸:', upload_to='partner', verbose_name='客户logo')),
                ('name', models.CharField(help_text='合作伙伴', max_length=20, verbose_name='客户名称')),
            ],
            options={
                'verbose_name': '合作伙伴',
                'verbose_name_plural': '合作伙伴',
                'db_table': 'partner',
            },
        ),
    ]
