# Generated by Django 4.1 on 2026-04-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='图片', upload_to='team', verbose_name='头像')),
                ('name', models.CharField(help_text='团队成员', max_length=200, verbose_name='姓名')),
                ('Job_position', models.CharField(help_text='职位名称', max_length=200, verbose_name='职位')),
            ],
            options={
                'verbose_name': '团队管理',
                'verbose_name_plural': '团队管理',
                'db_table': 'team',
            },
        ),
    ]
