# Generated by Django 4.1 on 2026-04-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序'),
        ),
    ]
