# Generated by Django 4.1 on 2026-04-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='slide/', verbose_name='封面图')),
                ('title', models.TextField(help_text='一级标题', verbose_name='一级标题')),
                ('content', models.TextField(help_text='二级标题', verbose_name='二级标题')),
            ],
            options={
                'verbose_name': '幻灯片管理',
                'verbose_name_plural': '幻灯片管理',
                'db_table': 'slide',
            },
        ),
    ]
