# Generated by Django 4.1 on 2026-04-20 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='slide',
            table=None,
        ),
    ]
