# Generated by Django 4.1 on 2026-04-20 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0002_alter_slide_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='slide',
            table='slide',
        ),
    ]
