# Generated by Django 4.1 on 2026-04-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0003_alter_slide_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=models.CharField(help_text='二级标题', max_length=200, verbose_name='二级标题'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, height_field='最佳尺寸:1920*1080', null=True, upload_to='slide', verbose_name='幻灯片'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(help_text='一级标题', max_length=200, verbose_name='一级标题'),
        ),
    ]
