# Generated by Django 4.1 on 2026-04-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0004_alter_slide_content_alter_slide_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, help_text='最佳尺寸:1920*1080', null=True, upload_to='slide', verbose_name='幻灯片'),
        ),
    ]
