# Generated by Django 4.1 on 2026-04-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0005_alter_slide_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='content_next',
            field=models.TextField(default='', help_text='二级标题', verbose_name='二级标题'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=models.TextField(default='', help_text='一级标题', verbose_name='一级标题'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(help_text='主标题', max_length=200, verbose_name='主标题'),
        ),
    ]
